services:
  api:
    build: .
    ports:
      - '4000:3000'
    env_file:
      - .env
    environment:
      - DB_CONNECTION_LINK=mongodb://db:27017/project-name
    depends_on:
      - db

  db:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: {}
