services:
  api:
    build: .
    ports:
      - '4000:4000'
    env_file:
      - .env
    environment:
      - DB_CONNECTION_LINK=mongodb://db:27017/hoa-hiep-phat
    depends_on:
      - db
    networks:
      - mooncake-net

  db:
    image: mongo
    ports:
      - '27018:27017'
    volumes:
      - mongodb_data:/data/db
    networks:
      - mooncake-net

volumes:
  mongodb_data: {}

networks:
  mooncake-net:
    external: true
